before_install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

language: java
jdk:
  - openjdk8
  - openjdk9
  - openjdk11
  - openjdk14
  - openjdk15

notifications:
  email: false

